spring.application.name=securebank-api
server.port=8080

# H2 in-memory database (data resets on every restart) 
spring.datasource.url=jdbc:h2:mem:securebank;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000

app.cors.allowed-origins=http://localhost:5500,http://127.0.0.1:5500,http://localhost:3000,http://127.0.0.1:5501
